<a href="https://colab.research.google.com/github/AJ-4-beep/MAT-421/blob/main/AJModDHW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Submit your Jupyter Notebook files to demonstrate the following concepts:  (Note: section numbers and topics from notes and not from the textbook)

Linear Algebra concepts such as linear space, orthogonality, eigenvalues.

Linear regression.

Linear Space: A linear space is built up of linear combinations of vectors. A linear combination of a vectors is a set of vectors multiplied by some scalar value to generate a new set of vectors.

Vectors are linearly independent if they cannot be written as another combination of vectors; if a vector cannot be written as another vector multiplied by a scalar, they are independent.

In [10]:
import numpy as np

vector = np.array([1,1,2])
vector2 = np.array([-2,-2,-4])

vector = vector * -2


print(vector)
print(vector2)
print( vector == vector2)

[-2 -2 -4]
[-2 -2 -4]
[ True  True  True]


The above code shows the idea of vectors that are linearly dependent, which is the opposite of being linearly dependent. The 2 vectors are initially (1,1,2) and (-2,-2,-4), which are evidently different from each other. However, by multiplying the first vector by the scalar -2, the first vector becomes (-2,-2,-4), which is equivalent to the second vector. Thus, these vectors are linearly dependent.

Orthogonality: In simple terms, orthagonality can be thought of as two perpendicular vectors, or vectors that will only cross at one point.

The idea of orthogonality is especially important with vectors and linear spaces because the orthogonal vectors help build orthogonal bases, which help build linear spaces out of small unit vectors. Essentially, orthogonal vectors, when reduced to their smallest form, a unit vector, can help build a linear space where all of the vectors are inherently linearly independent; this is useful because solutions to problems in this linear space will be linearly independent. That is to say that solutions in this space will be unique and identifiable.

A list of unit vectors that are pairwise orthogonal will therefore be named orthonormal.

Eigenvalues: Eigenvalues are values such that Ax = (lambda)x, where x represents some eigenvector, A is a matrix, and lambda is the eigenvalue. Essentially, it is a value that represents a solution equal to the matrix presented to you, and is useful when attempting to transform matrices.

However, not all matrices will have eigenvalues and eigenvectors.

In [11]:
from numpy.linalg import eig

x = np.array([[2,4], [-4, -8]])
w,v = eig(x)

print('Eigenvalue:', w)
print('Eigenvector:', v)

Eigenvalue: [ 0. -6.]
Eigenvector: [[ 0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]


As seen above, a square matrix with vectors (2,4) and (-4,-8) is made, and the eignevectors/values are found with the eig function. Essentially, eigenvalues and eigenvectors are a method to help transform matrices into different forms.

Linear Regression: Linear regression is, generally, a simple method to establish a linear relationship between data. QR decomposition is one method that can be used to decompose a matrix into 2 different matrices, that, when multiplied together, yield the original matrix.

In [12]:
from numpy.linalg import qr

A = np.array([[2,6], [8,14]])

Q,R = qr(A)
print('Q:', Q)
print('R:', R)

y = np.dot(Q,R)
print('QR:', y)

iterations = [1,20]
for i in range(20):
  Q,R = qr(x)
  x = np.dot(R,Q)
  if i+1 in iterations:
    print(f'Iteration {i+1}:')
    print(x)

Q: [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]
R: [[ -8.24621125 -15.03720875]
 [  0.          -2.42535625]]
QR: [[ 2.  6.]
 [ 8. 14.]]
Iteration 1:
[[-6.00000000e+00 -8.00000000e+00]
 [-7.94410929e-16 -3.97205465e-16]]
Iteration 20:
[[-6.00000000e+000  8.00000000e+000]
 [-5.14737352e-319  6.62009108e-016]]


The above code takes in a matrix A, and generates two matrices Q and R in order to help find their decomposed matrices. The overall function of this is to help generate simpler matrices that can assist in the creation of a linear regression model. The problem of the "least squares" method is resolved by using the QR method to help convert the matrices' data into coefficients for the overall equation.